SELECT
  W.ID
FROM
  WEATHER W
  JOIN WEATHER W1 ON W.RECORDDATE = DATE_ADD (W1.RECORDDATE, INTERVAL 1 DAY)
  AND W.TEMPERATURE > W1.TEMPERATURE;

SELECT
  W.ID
FROM
  WEATHER W,
  WEATHER W1
WHERE
  W.TEMPERATURE > W1.TEMPERATURE
  AND DATEDIFF (W.RECORDDATE, W1.RECORDDATE) = 1;